version: "3.9"

services:
  # Ollama backend
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:11434/api/tags || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  # Descarga automática del modelo
  model-downloader:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    command: >
      sh -c "
        echo 'Esperando a que Ollama esté listo...' &&
        until curl -sf http://ollama:11434/api/tags; do
          echo 'Ollama no está listo, reintentando en 2s...';
          sleep 2;
        done &&
        echo 'Ollama está listo. Descargando modelo LLaVA...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"llava:13b\"}' &&
        echo 'Modelo descargado exitosamente'
      "
    restart: "no"

  # API wrapper
  crop-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    expose:
      - "8080"
    depends_on:
      - model-downloader
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # HTTPS proxy con Caddy
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - crop-api

volumes:
  ollama_data:
  caddy_data:
  caddy_config:
