name: Auto Deploy to VPS

on:
  push:
    branches:
      - main  # Cambia esta rama si usas una diferente, como 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Copy files to VPS
        run: |
          ssh -o StrictHostKeyChecking=no jlopep09@vps.joselp.com "git -C /home/jlopep09/repository/GreenHouseIOT pull || git clone https://github.com/your_user/your_repo.git /home/jlopep09/repository/GreenHouseIOT"
      
      - name: Deploy using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no jlopep09@vps.joselp.com "cd /home/jlopep09/repository/GreenHouseIOT && docker compose pull && docker compose --profile all up --build"
